name: Build Web App

on:
  push:
    branches:
      - dev
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
  applicationfolder: dotNetLegacy

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Configure Git
        run: git config --global url.'https://${{ secrets.SPECIAL_TOKEN }}:@github.com'.insteadOf 'https://github.com'

      - uses: actions/checkout@v3
        name: Checkout Code

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2

      - name: Restore NuGet Packages
        working-directory: ${{ env.applicationfolder }}
        run: nuget restore webapplication3.sln

      - name: Build and Publish Web App
        working-directory: ${{ env.applicationfolder }}
        run: msbuild webapplication3.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile /p:PublishProfileRootFolder="C:\Users\Administrator\source\repos\WebApplication3\WebApplication3\Properties\PublishProfiles\"
